/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_x264encoderdemo_AVFilterHelper */

#ifndef _Included_com_test_x264encoderdemo_AVFilterHelper
#define _Included_com_test_x264encoderdemo_AVFilterHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_x264encoderdemo_AVFilterHelper
 * Method:    initAVFilterHelper
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_test_x264encoderdemo_AVFilterHelper_initAVFilterHelper
  (JNIEnv *, jclass, jint, jint,jint);

/*
 * Class:     com_test_x264encoderdemo_AVFilterHelper
 * Method:    addWatermark
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_test_x264encoderdemo_AVFilterHelper_addWatermark
  (JNIEnv *, jclass, jbyteArray, jint,jbyteArray);

/*
 * Class:     com_test_x264encoderdemo_AVFilterHelper
 * Method:    closeAVFilterHelper
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_x264encoderdemo_AVFilterHelper_closeAVFilterHelper
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
