/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seuic_jni_Mp4v2Helper */

#ifndef _Included_Java_com_test_x264encoderdemo_Mp4v2Helper
#define _Included_Java_com_test_x264encoderdemo_Mp4v2Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seuic_jni_Mp4v2Helper
 * Method:    initMp4Encoder
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_test_x264encoderdemo_Mp4v2Helper_initMp4Encoder
  (JNIEnv *, jclass, jstring, jint, jint , jint);

/*
 * Class:     com_seuic_jni_Mp4v2Helper
 * Method:    mp4VEncode
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL JJava_com_test_x264encoderdemo_Mp4v2Helper_mp4VEncode
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_seuic_jni_Mp4v2Helper
 * Method:    closeMp4Encoder
 * Signature: ()V
 */
JNIEXPORT void JNICALLJava_com_test_x264encoderdemo_Mp4v2Helper_closeMp4Encoder
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
